// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvweYlbNGsop87SuNgBSv4UgFG8I1hDfU',
    appId: '1:953421428964:web:e8a5e81a9b11e3dcc4d4f1',
    messagingSenderId: '953421428964',
    projectId: 'arcova-65203',
    authDomain: 'arcova-65203.firebaseapp.com',
    storageBucket: 'arcova-65203.firebasestorage.app',
    measurementId: 'G-MGZBME62XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkayWPhXa5MDKIeID2Usv0G_OXOMD263o',
    appId: '1:953421428964:android:ad6f441e4269c239c4d4f1',
    messagingSenderId: '953421428964',
    projectId: 'arcova-65203',
    storageBucket: 'arcova-65203.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDO-g7U9ySemUR2eoBCOYRtMZXVVyjiNI',
    appId: '1:953421428964:ios:3bae343eaff6a38cc4d4f1',
    messagingSenderId: '953421428964',
    projectId: 'arcova-65203',
    storageBucket: 'arcova-65203.firebasestorage.app',
    iosBundleId: 'com.arcova.well',
  );

static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvweYlbNGsop87SuNgBSv4UgFG8I1hDfU',
    appId: '1:953421428964:web:ba834a05f43d8ab6c4d4f1',
    messagingSenderId: '953421428964',
    projectId: 'arcova-65203',
    authDomain: 'arcova-65203.firebaseapp.com',
    storageBucket: 'arcova-65203.firebasestorage.app',
    measurementId: 'G-E1S6TBGTEX',
  );
}
