import 'package:flutter/material.dart';
import '../../../../core/theme/app_theme.dart';

class DataDisclosureScreen extends StatelessWidget {
  const DataDisclosureScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: const Text('Data Use Disclosure')),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(20, 16, 20, 32),
        children: [
          _Section(
            icon: Icons.mood,
            title: 'Mood & Energy Check-Ins',
            body:
                'Your mood, energy, and stress scores are stored locally on your device using Hive. '
                'They are only uploaded to the cloud when you are signed in and have an active premium subscription.',
          ),
          _Section(
            icon: Icons.monitor_heart_outlined,
            title: 'Health Metrics',
            body:
                'On Android, Arcova requests read-only access to sleep, steps, active minutes, and '
                'resting heart rate via Health Connect. These values are stored locally and, if you '
                'choose, backed up to your private Firestore document. Arcova never sells or shares '
                'your health data with third parties.',
          ),
          _Section(
            icon: Icons.cloud_outlined,
            title: 'Cloud Backup',
            body:
                'Cloud backup is optional and requires a Google account and an active premium '
                'subscription. Your data is stored in a Firestore document accessible only to your '
                'account (uid-scoped security rules). You can delete all cloud data at any time '
                'from Settings → Wipe and Reset.',
          ),
          _Section(
            icon: Icons.psychology_outlined,
            title: 'AI Briefings',
            body:
                'Daily briefings are generated by Gemini via Firebase AI Logic. Your health snapshot '
                'and mood check-in for the day are sent to the model to produce your briefing. '
                'No personally identifying information beyond that snapshot is transmitted. '
                'If the cloud model is unavailable, briefings are generated fully on-device.',
          ),
          _Section(
            icon: Icons.delete_outline,
            title: 'Deleting Your Data',
            body:
                'You can wipe all local data and your cloud backup at any time from '
                'Settings → Wipe and Reset. This permanently removes all stored records '
                'from both your device and Firestore.',
          ),
        ],
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final IconData icon;
  final String title;
  final String body;
  const _Section({required this.icon, required this.title, required this.body});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 20),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: AppTheme.tertiaryColor, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: theme.textTheme.titleSmall
                        ?.copyWith(fontWeight: FontWeight.w600)),
                const SizedBox(height: 4),
                Text(body,
                    style:
                        theme.textTheme.bodyMedium?.copyWith(height: 1.5)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
